name: Publish to Chrome Web Store

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  pack-addon:
    uses: ./.github/workflows/pack_addon.yml
    with:
      addonType: 'chrome'
  publish:
    runs-on: ubuntu-latest
    needs: pack-addon
    steps:
      - name: Download packed addon artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.pack-addon.outputs.artifactName }}
          path: packed-addon
          
      - name: Upload extension
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
         file-path: ${{ format("packed-addon/{0}", needs.pack-addon.outputs.zipFileName) }}
         extension-id: ${{ secrets.CHROME_WEB_EXTENSION_ID }}
         client-id: ${{ secrets.CHROME_WEB_CLIENT_ID }}
         client-secret: ${{ secrets.CHROME_WEB_CLIENT_SECRET }}
         refresh-token: ${{ secrets.CHROME_WEB_REFRESH_TOKEN }}
         publish: false
