name: Publish to Chrome Web Store

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  pack-addon:
    pack-chrome-addon:
      uses: ./.github/workflows/pack_addon.yml
      with:
        addonType: 'chrome'
  publish:
    runs-on: ubuntu-latest
    needs: pack-addon
    steps:
      - name: Upload extension
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
         file-path: ${{ needs.pack-addon.outputs.packFileName }}
         extension-id: ${{ secrets.CHROME_WEB_EXTENSION_ID }}
         client-id: ${{ secrets.CHROME_WEB_CLIENT_ID }}
         client-secret: ${{ secrets.CHROME_WEB_CLIENT_SECRET }}
         refresh-token: ${{ secrets.CHROME_WEB_REFRESH_TOKEN }}
         publish: false
