name: Publish to Chrome Web Store
on:
 push:
    tags:
      - v*
env:
 FINAL_ZIP_NAME: ${{ format('dist/RemoveTwitterViews-{0}.zip', ${{github.ref_name}}) }}

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
         type: 'zip'
         filename: $FINAL_ZIP_NAME
       
      - name: Upload extension
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
         file-path: $FINAL_ZIP_NAME
         extension-id: idndmhfalcddnfpafjkkjocmpoofgdbl
         client-id: ${{ secrets.CHROME_WEB_CLIENT_ID }}
         client-secret: ${{ secrets.CHROME_WEB_CLIENT_SECRET }}
         refresh-token: ${{ secrets.CHROME_WEB_REFRESH_TOKEN }}
         publish: true
