name: Publish to Firefox Addon Gallery

on:
  push:
    tags:
      - v*

  workflow_dispatch:
env:
  RUN_IDENTIFIER: run-${{ github.run_id }}-${{ github.run_attempt }}
jobs:
  pack-addon:
    uses: ./.github/workflows/pack_addon.yml
    with:
      addonType: 'firefox'
  publish:
    runs-on: ubuntu-latest
    needs: pack-addon
    steps:
      - name: Download packed addon artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.pack-addon.outputs.artifactName }}
          path: packed-addon-artifact
    
      - name: Get JWT issue and expiration date
        id: date
        run: |
          echo "issueDate=$(date -u +%s)" >> $GITHUB_OUTPUT
          echo "expDate=$(date -d '+4 minutes' -u +%s)" >> $GITHUB_OUTPUT
    
      - name: Generate JWT token
        id: jwt-token-generate
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: ${{ secrets.FIREFOX_GALLERY_API_SECRET }}
          payload: > 
            {
              "iat": "${{ steps.date.outputs.issueDate }}",
              "exp": "${{ steps.date.outputs.expDate }}",
              "jti": "${{ env.RUN_IDENTIFIER }}",
              "iss": "${{ secrets.FIREFOX_GALLERY_API_SECRET }}"
            }

      - name: Upload firefox addon
        id: firefox-upload-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://addons.mozilla.org/api/v5/addons/upload"
          method: 'POST'
          bearerToken: ${{ steps.jwt-token-generate.outputs.token }}
          contentType: multipart/form-data
          data: '{ "channel ": "listed" }'
          files: '{ "upload": "packed-addon-artifact/${{ needs.pack-addon.outputs.zipFileName }}" }'
