name: Publish firefox/chrome addons

on:
  push:
    tags:
      - v*
env:
  RUN_IDENTIFIER: run-${{ github.run_id }}-${{ github.run_attempt }}
  ARTIFACT_NAME: packed-addons-${{ github.ref_name }}
jobs:
  pack-addons:
    runs-on: ubuntu-latest
    outputs:
      chromeZipFileName: ${{ steps.pack-project.outputs.chromeZip }}
      firefoxZipFileName: ${{ steps.pack-project.outputs.firefoxZip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Install node dependencies
        id: install-dependencies
        run: npm i

      - name: Pack project and get zip filenames
        id: pack-project
        run: |
          PACK_OUTPUT=$(npm run pack)
          FIREFOX_ZIP_FILE=$(echo $PACK_OUTPUT | awk '/firefox-file: .*\.zip$/{print $NF}')
          CHROME_ZIP_FILE=$(echo $PACK_OUTPUT | awk '/chrome-file: .*\.zip$/{print $NF}')
          echo "firefoxZip=$FIREFOX_ZIP_FILE" >> $GITHUB_OUTPUT
          echo "chromeZip=$CHROME_ZIP_FILE" >> $GITHUB_OUTPUT
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          if-no-files-found: error
          path: |
            ${{ steps.pack-project.outputs.chromeZip }}
            ${{ steps.pack-project.outputs.firefoxZip }}
            
  publish-firefox:
    runs-on: ubuntu-latest
    needs: pack-addons
    steps:
      - name: Download packed addon artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: packed-addon-artifact

      - name: Get JWT issue and expiration date
        id: date
        run: |
          echo "issueDate=$(date -u +%s)" >> $GITHUB_OUTPUT
          echo "expDate=$(date -d '+4 minutes' -u +%s)" >> $GITHUB_OUTPUT

      - name: Generate JWT token
        id: jwt-token-generate
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: ${{ secrets.FIREFOX_GALLERY_API_SECRET }}
          payload: >
            {
              "iat": ${{ steps.date.outputs.issueDate }},
              "exp": ${{ steps.date.outputs.expDate }},
              "jti": "${{ env.RUN_IDENTIFIER }}",
              "iss": "${{ secrets.FIREFOX_GALLERY_API_KEY }}"
            }

      - name: Upload firefox addon
        id: firefox-upload-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://addons.mozilla.org/api/v5/addons/upload/"
          method: "POST"
          customHeaders: '{"Authorization": "JWT ${{ steps.jwt-token-generate.outputs.token }}" }'
          contentType: multipart/form-data
          data: '{ "channel": "listed" }'
          files: '{ "upload": "packed-addon-artifact/${{ needs.pack-addons.outputs.firefoxZipFileName }}" }'

      - name: Wait for upload validation
        id: firefox-validation-request
        uses: mydea/action-wait-for-api@v1
        with:
          url: ${{ fromJson(steps.firefox-upload-request.outputs.response).url }}
          method: "GET"
          headers: '{"Authorization" : "JWT ${{ steps.jwt-token-generate.outputs.token }}" }'
          expected-response-field: "processed"
          expected-response-field-value: "true"
          timeout: 300
          interval: 5

      - name: Create new addon version
        id: firefox-version-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://addons.mozilla.org/api/v5/addons/addon/${{ secrets.FIREFOX_GALLERY_ADDON_IDENTIFIER }}/versions/"
          method: "POST"
          customHeaders: '{"Authorization": "JWT ${{ steps.jwt-token-generate.outputs.token }}" }'
          contentType: application/json
          data: '{ "upload": "${{ fromJson(steps.firefox-upload-request.outputs.response).uuid }}" }'
  publish-chrome:
    runs-on: ubuntu-latest
    needs: pack-addons
    steps:
      - name: Download packed addon artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: packed-addon-artifact

      - name: Upload extension
        uses: mnao305/chrome-extension-upload@v4.0.0
        with:
          file-path: ${{ format('packed-addon-artifact/{0}', needs.pack-addons.outputs.chromeZipFileName) }}
          extension-id: ${{ secrets.CHROME_WEB_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_WEB_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEB_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEB_REFRESH_TOKEN }}
          publish: true